### PR TITLE
added portaudio as 3rdparty lib for sound IO

### PR DESCRIPTION
**Pull request by alexanderlerch**

### CODE REVIEW

**Review by Jas1238Smith — COMMENTED** [review]
Is there any reason to include the empty files? Other than that, it all seems intact.

**Comment by alexanderlerch** [comment]
what empty files?

**Comment by Jas1238Smith** [comment]
> what empty files?

There are a few empty files in `3rdparty` like `3rdparty/portaudio-master/bindings/cpp/NEWS`, `3rdparty/portaudio-master/bindings/cpp/README`, `3rdparty/portaudio-master/bindings/cpp/build/gnu/OUT_OF_DATE`.

If they're just normal parts of the PortAudio installation, then there's not an issue - I just wanted to bring it to your attention.

**Comment by alexanderlerch** [comment]
Oh I see. I didn't pay close attention. While I didn't commit files that I knew for sure we wouldn't need, I committed definitely more than needed. This is part of PortAudio, but we could remove it if we want to.

**Comment by alexanderlerch** [comment]
@Jas1238Smith  I'll leave that decision to you, feel free to delete or merge as is.

**Pull request merged**
